create table if not exists public.invitations (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    password text not null,
    subtitle text,
    date date not null,
    time_start time not null,
    time_end time not null,
    venue text,
    address text,
    maps_url text,
    dress_code text,
    dress_description text,
    dress_colors_not_allowed text,
    alias text,
    cbu text,
    gift_text text,
    hero_image text,
    template text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.invitations
add column if not exists dress_colors_not_allowed text;

create table if not exists public.rsvps (
    id bigint generated by default as identity primary key,
    slug text not null references public.invitations(slug) on delete cascade,
    name text not null,
    restriction text not null default 'Ninguna',
    allergy text,
    detail text,
    created_at timestamptz not null default now()
);

alter table public.rsvps
add column if not exists allergy text;

alter table public.invitations enable row level security;
alter table public.rsvps enable row level security;

create policy "public can read invitations"
on public.invitations for select
to anon
using (true);

create policy "public can create invitations"
on public.invitations for insert
to anon
with check (true);

create policy "public can update invitations"
on public.invitations for update
to anon
using (true)
with check (true);

drop policy if exists "public can delete invitations" on public.invitations;

create policy "public can delete invitations"
on public.invitations for delete
to anon
using (true);

create policy "public can read rsvps"
on public.rsvps for select
to anon
using (true);

create policy "public can create rsvps"
on public.rsvps for insert
to anon
with check (true);